using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using shipapp.Models.ModelData;

namespace shipapp.Models
{
    /// <summary>
    /// Carrier Model Class
    /// </summary>
    class Carrier
    {
        /// <summary>
        /// Autogenerated ID Do mot modify
        /// </summary>
        public long CarrierId { get; set; }
        /// <summary>
        /// Carrier name as string
        /// </summary>
        public string CarrierName { get; set; }
        /// <summary>
        /// Identifyer in supplement tables, as string, max value 1000 bits and MUST be unique across all primary models
        /// </summary>
        public string Carrier_PersonId { get; set; }
        /// <summary>
        /// Carrier Phone Number as PhoneNumber
        /// </summary>
        public PhoneNumber PhoneNumber { get; set; }
        /// <summary>
        /// Carrier Notes as List of Note
        /// </summary>
        public List<Note> Notes { get; set; }
        /// <summary>
        /// Constructor
        /// </summary>
        public Carrier()
        {
            Notes = new List<Note>() { };
        }
    }
}
