using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using shipapp.Models.ModelData;

namespace shipapp.Models
{
    /// <summary>
    /// Vendor Model Class
    /// </summary>
    class Vendors
    {
        /// <summary>
        /// Autogenerated Id Do not modify
        /// </summary>
        public long VendorId { get; set; }
        /// <summary>
        /// Vendor Name as string
        /// </summary>
        public string VendorName { get; set; }
        /// <summary>
        /// Vendor address as PhysicalAddress
        /// </summary>
        public PhysicalAddress VendorAddress { get; set; }
        /// <summary>
        /// Vendor point of contact as string
        /// </summary>
        public string VendorPointOfContactName { get; set; }
        /// <summary>
        /// Vendor phone as PhoneNumber
        /// </summary>
        public PhoneNumber VendorPhone { get; set; }
        /// <summary>
        /// Vendor Notes as List of Note
        /// </summary>
        public List<Note> Notes { get; set; }
        public Vendors()
        {
            Notes = new List<Note>() { };
        }
    }
}
